#settings
GiveItemsOnJoin: true
GiveItemsOnRespawn: true
ClearItemsAfterUse: false
workingworlds:
- Hubria
#please dont add more slots

//slot1: 0
//slot1-Tip: 
//slot1-command: 

///slot2: 0
//slot2-Tip: 
//slot2-command: 

//slot3: 0
//slot3-Tip: 
//slot3-command: 

//slot4: 0
//slot4-Tip: 
//slot4-command: 

//slot5: 0
//slot5-Tip: 
//slot5-command: 

//slot6: 0
//slot6-Tip: 
//slot6-command: 

//slot7: 0
//slot7-Tip: 
//slot7-command: 

slot8: 347
slot8-Tip: 
slot8-command: 

// add from here!

slot9: 0
slot9-Tip: 
slot9-command: 

slot10: 340
slot10-Tip: 
slot10-command: 

